(function() {var implementors = {};
implementors["concert"] = [{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"concert/struct.Concert.html\" title=\"struct concert::Concert\">Concert</a>","synthetic":false,"types":["concert::Concert"]}];
implementors["concert_io"] = [{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"concert_io/struct.TokenMetadata.html\" title=\"struct concert_io::TokenMetadata\">TokenMetadata</a>","synthetic":false,"types":["concert_io::TokenMetadata"]}];
implementors["dao"] = [{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"dao/struct.Proposal.html\" title=\"struct dao::Proposal\">Proposal</a>","synthetic":false,"types":["dao::Proposal"]}];
implementors["dao_light"] = [{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"dao_light/struct.Proposal.html\" title=\"struct dao_light::Proposal\">Proposal</a>","synthetic":false,"types":["dao_light::Proposal"]}];
implementors["dutch_auction"] = [{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"enum\" href=\"dutch_auction/state/enum.Status.html\" title=\"enum dutch_auction::state::Status\">Status</a>","synthetic":false,"types":["dutch_auction::state::Status"]},{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"dutch_auction/struct.NFT.html\" title=\"struct dutch_auction::NFT\">NFT</a>","synthetic":false,"types":["dutch_auction::NFT"]},{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"dutch_auction/struct.Auction.html\" title=\"struct dutch_auction::Auction\">Auction</a>","synthetic":false,"types":["dutch_auction::Auction"]}];
implementors["gear_feeds_channel"] = [{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"gear_feeds_channel/struct.Channel.html\" title=\"struct gear_feeds_channel::Channel\">Channel</a>","synthetic":false,"types":["gear_feeds_channel::Channel"]}];
implementors["lt_io"] = [{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"lt_io/struct.Player.html\" title=\"struct lt_io::Player\">Player</a>","synthetic":false,"types":["lt_io::Player"]}];
implementors["market_io"] = [{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"market_io/struct.Auction.html\" title=\"struct market_io::Auction\">Auction</a>","synthetic":false,"types":["market_io::Auction"]},{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"market_io/struct.Item.html\" title=\"struct market_io::Item\">Item</a>","synthetic":false,"types":["market_io::Item"]}];
implementors["multitoken"] = [{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"multitoken/struct.SimpleMTK.html\" title=\"struct multitoken::SimpleMTK\">SimpleMTK</a>","synthetic":false,"types":["multitoken::SimpleMTK"]}];
implementors["nft"] = [{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"nft/struct.NFT.html\" title=\"struct nft::NFT\">NFT</a>","synthetic":false,"types":["nft::NFT"]}];
implementors["nft_marketplace"] = [{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"nft_marketplace/struct.Market.html\" title=\"struct nft_marketplace::Market\">Market</a>","synthetic":false,"types":["nft_marketplace::Market"]}];
implementors["staking_io"] = [{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"staking_io/struct.Staker.html\" title=\"struct staking_io::Staker\">Staker</a>","synthetic":false,"types":["staking_io::Staker"]}];
implementors["supply_chain_io"] = [{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"supply_chain_io/struct.ItemInfo.html\" title=\"struct supply_chain_io::ItemInfo\">ItemInfo</a>","synthetic":false,"types":["supply_chain_io::ItemInfo"]},{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"enum\" href=\"supply_chain_io/enum.ItemState.html\" title=\"enum supply_chain_io::ItemState\">ItemState</a>","synthetic":false,"types":["supply_chain_io::ItemState"]}];
if (window.register_implementors) {window.register_implementors(implementors);} else {window.pending_implementors = implementors;}})()