(function() {var implementors = {};
implementors["concert_io"] = [{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"struct\" href=\"concert_io/struct.TokenMetadata.html\" title=\"struct concert_io::TokenMetadata\">TokenMetadata</a>","synthetic":false,"types":["concert_io::TokenMetadata"]}];
implementors["dao"] = [{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"struct\" href=\"dao/struct.Proposal.html\" title=\"struct dao::Proposal\">Proposal</a>","synthetic":false,"types":["dao::Proposal"]},{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"struct\" href=\"dao/struct.Member.html\" title=\"struct dao::Member\">Member</a>","synthetic":false,"types":["dao::Member"]}];
implementors["dao_io"] = [{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"enum\" href=\"dao_io/enum.Vote.html\" title=\"enum dao_io::Vote\">Vote</a>","synthetic":false,"types":["dao_io::Vote"]}];
implementors["dao_light"] = [{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"struct\" href=\"dao_light/struct.Proposal.html\" title=\"struct dao_light::Proposal\">Proposal</a>","synthetic":false,"types":["dao_light::Proposal"]},{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"struct\" href=\"dao_light/struct.Member.html\" title=\"struct dao_light::Member\">Member</a>","synthetic":false,"types":["dao_light::Member"]}];
implementors["dao_light_io"] = [{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"enum\" href=\"dao_light_io/enum.Vote.html\" title=\"enum dao_light_io::Vote\">Vote</a>","synthetic":false,"types":["dao_light_io::Vote"]}];
implementors["dutch_auction"] = [{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"enum\" href=\"dutch_auction/state/enum.Status.html\" title=\"enum dutch_auction::state::Status\">Status</a>","synthetic":false,"types":["dutch_auction::state::Status"]}];
implementors["escrow_io"] = [{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"struct\" href=\"escrow_io/struct.Wallet.html\" title=\"struct escrow_io::Wallet\">Wallet</a>","synthetic":false,"types":["escrow_io::Wallet"]},{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"enum\" href=\"escrow_io/enum.WalletState.html\" title=\"enum escrow_io::WalletState\">WalletState</a>","synthetic":false,"types":["escrow_io::WalletState"]}];
implementors["lt_io"] = [{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"struct\" href=\"lt_io/struct.Player.html\" title=\"struct lt_io::Player\">Player</a>","synthetic":false,"types":["lt_io::Player"]}];
implementors["market_io"] = [{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"struct\" href=\"market_io/struct.Offer.html\" title=\"struct market_io::Offer\">Offer</a>","synthetic":false,"types":["market_io::Offer"]},{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"struct\" href=\"market_io/struct.Auction.html\" title=\"struct market_io::Auction\">Auction</a>","synthetic":false,"types":["market_io::Auction"]},{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"struct\" href=\"market_io/struct.Bid.html\" title=\"struct market_io::Bid\">Bid</a>","synthetic":false,"types":["market_io::Bid"]},{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"struct\" href=\"market_io/struct.Item.html\" title=\"struct market_io::Item\">Item</a>","synthetic":false,"types":["market_io::Item"]}];
implementors["staking_io"] = [{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"struct\" href=\"staking_io/struct.Staker.html\" title=\"struct staking_io::Staker\">Staker</a>","synthetic":false,"types":["staking_io::Staker"]}];
implementors["supply_chain_io"] = [{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"struct\" href=\"supply_chain_io/struct.ItemInfo.html\" title=\"struct supply_chain_io::ItemInfo\">ItemInfo</a>","synthetic":false,"types":["supply_chain_io::ItemInfo"]},{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"enum\" href=\"supply_chain_io/enum.ItemState.html\" title=\"enum supply_chain_io::ItemState\">ItemState</a>","synthetic":false,"types":["supply_chain_io::ItemState"]}];
if (window.register_implementors) {window.register_implementors(implementors);} else {window.pending_implementors = implementors;}})()